name: Build - Windows
description: 'Build Windows release'

runs:
  using: "composite"
  steps:

  - name: Set path for candle and light
    run: echo "C:\Program Files (x86)\WiX Toolset v3.11\bin" >> $GITHUB_PATH
    shell: bash

  - name: Build Bamboo cli wallet
    run: dotnet publish cli --configuration Release --self-contained -r win-x64 -p:PublishReadyToRun=true --output install\windows\BambooWalletInstaller\bin\BambooWalletCliFiles
    shell: powershell

  - name: Harvest Bamboo cli wallet
    run: |
      dir install\windows\BambooWalletInstaller\bin\BambooWalletCliFiles
      heat.exe dir install\windows\BambooWalletInstaller\bin\BambooWalletCliFiles -sreg -dr Bamboo -cg BambooWalletInstallationFilesGroup -gg -g1 -sf -srd -var "var.BambooWalletInstallationDirectory" -t install\windows\BambooWalletInstaller\remove_exe.xslt  -out install\windows\BambooWalletInstaller\wallet_files.wxs
    shell: cmd

  - name: Build installer
    run: |
      candle.exe -wx -dBambooWalletInstallationDirectory=install\windows\BambooWalletInstaller\bin\BambooWalletCliFiles -d"DevEnvDir=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\\" -dSolutionDir=install\windows\BambooWalletInstaller\ -dSolutionExt=.sln -dSolutionFileName=BambooWalletInstaller.sln -dSolutionName=BambooWalletInstaller -dSolutionPath=install\windows\BambooWalletInstaller\BambooWalletInstaller.sln -dConfiguration=Release -dOutDir=install\windows\BambooWalletInstaller\bin\x64\Release\ -dPlatform=x64 -dProjectDir=install\windows\BambooWalletInstaller\ -dProjectExt=.wixproj -dProjectFileName=BambooWalletInstaller.wixproj -dProjectName=BambooWalletInstaller -dProjectPath=install\windows\BambooWalletInstaller\BambooWalletInstaller.wixproj -dTargetDir=install\windows\BambooWalletInstaller\bin\x64\Release\ -dTargetExt=.msi -dTargetFileName=cypher-bamboo_${{ env.VERSION }}.msi -dTargetName=cypher-bamboo_${{ env.VERSION }} -dTargetPath=install\windows\BambooWalletInstaller\bin\x64\Release\cypher-bamboo_${{ env.VERSION }}.msi -out install\windows\BambooWalletInstaller\obj\x64\Release\ -pedantic -arch x64 -ext "C:\Program Files (x86)\WiX Toolset v3.11\bin\\WixUtilExtension.dll" -ext "C:\Program Files (x86)\WiX Toolset v3.11\bin\\WixUIExtension.dll" install\windows\BambooWalletInstaller\Product.wxs install\windows\BambooWalletInstaller\wallet_files.wxs
      Light.exe -b install\windows\BambooWalletInstaller -out install\windows\BambooWalletInstaller\bin\x64\Release\cypher-bamboo_${{ env.VERSION }}.msi -pdbout install\windows\BambooWalletInstaller\bin\x64\Release\cypher-bamboo_${{ env.VERSION }}.wixpdb -wx -cultures:null -ext "C:\Program Files (x86)\WiX Toolset v3.11\bin\\WixUtilExtension.dll" -ext "C:\Program Files (x86)\WiX Toolset v3.11\bin\\WixUIExtension.dll" -pedantic -contentsfile install\windows\BambooWalletInstaller\obj\x64\Release\BambooWalletInstaller.wixproj.BindContentsFileListnull.txt -outputsfile install\windows\BambooWalletInstaller\obj\x64\Release\BambooWalletInstaller.wixproj.BindOutputsFileListnull.txt -builtoutputsfile install\windows\BambooWalletInstaller\obj\x64\Release\BambooWalletInstaller.wixproj.BindBuiltOutputsFileListnull.txt -wixprojectfile install\windows\BambooWalletInstaller\BambooWalletInstaller.wixproj install\windows\BambooWalletInstaller\obj\x64\Release\Product.wixobj install\windows\BambooWalletInstaller\obj\x64\Release\wallet_files.wixobj
    shell: cmd

  - name: Calculate SHA256
    run: sha256sum install/windows/BambooWalletInstaller/bin/x64/Release/cypher-bamboo_${{ env.VERSION }}.msi > install/windows/BambooWalletInstaller/bin/x64/Release/cypher-bamboo_${{ env.VERSION }}.msi.sha256
    shell: bash

  - name: Copy artifacts
    run:  |
      move-item install/windows/BambooWalletInstaller/bin/x64/Release/cypher-bamboo_${{ env.VERSION }}.msi ${{ github.workspace }}
      move-item install/windows/BambooWalletInstaller/bin/x64/Release/cypher-bamboo_${{ env.VERSION }}.msi.sha256 ${{ github.workspace }}
    shell: powershell